# Generated by Django 6.0.7 on 2026-09-02 13:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Admin')], default='buyer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('crypto_wallet_address', models.CharField(blank=True, help_text='Web3 Wallet Address (ETH, SOL, BTC, USDT)', max_length=128)),
                ('preferred_currency', models.CharField(choices=[('ETH', 'Ethereum (ETH)'), ('SOL', 'Solana (SOL)'), ('BTC', 'Bitcoin (BTC)'), ('USDT', 'Tether (USDT)')], default='ETH', max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True)),
                ('is_verified_seller', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LandListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(help_text='City, State/Region, Country', max_length=255)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('price_crypto', models.DecimalField(decimal_places=6, max_digits=18)),
                ('crypto_currency', models.CharField(choices=[('ETH', 'ETH'), ('SOL', 'SOL'), ('BTC', 'BTC'), ('USDT', 'USDT')], default='ETH', max_length=10)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('size_sqm', models.DecimalField(decimal_places=2, help_text='Size in Square Meters', max_digits=12)),
                ('size_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('zoning_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('agricultural', 'Agricultural'), ('industrial', 'Industrial'), ('waterfront', 'Waterfront'), ('recreational', 'Recreational')], default='residential', max_length=50)),
                ('parcel_id', models.CharField(help_text='Deed / Cadastral Government ID', max_length=100, unique=True)),
                ('deed_verified', models.BooleanField(default=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='land_images/')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('available', 'Available'), ('under_contract', 'Under Contract'), ('sold', 'Sold'), ('rejected', 'Rejected')], default='available', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='land_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.landlisting')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_price_crypto', models.DecimalField(decimal_places=6, max_digits=18)),
                ('crypto_currency', models.CharField(default='ETH', max_length=10)),
                ('offer_price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buyer_wallet_address', models.CharField(max_length=128)),
                ('seller_wallet_address', models.CharField(blank=True, max_length=128)),
                ('escrow_wallet_address', models.CharField(blank=True, default='0x71C7656EC7ab88b098defB751B7401B5f6d8976F', max_length=128)),
                ('tx_hash', models.CharField(blank=True, help_text='Blockchain Tx Hash', max_length=128, null=True)),
                ('status', models.CharField(choices=[('offer_submitted', 'Offer Submitted'), ('accepted', 'Offer Accepted'), ('payment_pending', 'Payment Pending'), ('escrow_locked', 'Escrow Locked (Verification)'), ('completed', 'Completed & Transferred'), ('rejected', 'Offer Rejected'), ('cancelled', 'Cancelled')], default='offer_submitted', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_transactions', to=settings.AUTH_USER_MODEL)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.landlisting')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='app.landlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_lands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'land')},
            },
        ),
    ]
