# Generated by Django 6.0.7 on 2026-09-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlisting',
            name='lga',
            field=models.CharField(blank=True, help_text='Local Government Area (LGA)', max_length=100),
        ),
        migrations.AddField(
            model_name='landlisting',
            name='state',
            field=models.CharField(blank=True, help_text='Nigerian State / FCT', max_length=50),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='location',
            field=models.CharField(help_text='City/Area, State, Country (e.g. Lekki Phase 1, Lagos State)', max_length=255),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='parcel_id',
            field=models.CharField(help_text='Title Document / Survey Plan No. (e.g. C of O No. 2026/8819)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='size_acres',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size in Acres/Hectares', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='size_sqm',
            field=models.DecimalField(decimal_places=2, help_text='Land Area in Square Meters (Sqm)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='zoning_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('agricultural', 'Agricultural'), ('industrial', 'Industrial'), ('mixed_use', 'Mixed-Use'), ('waterfront', 'Waterfront')], default='residential', max_length=50),
        ),
    ]
