# Generated by Django 6.0.7 on 2026-09-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_landlisting_lga_landlisting_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlisting',
            name='parcel_id',
            field=models.CharField(blank=True, help_text='Title Document / Survey Plan No. (e.g. C of O No. 2026/8819)', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
