# Generated by Django 6.0.7 on 2026-09-02 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_landlisting_parcel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_currency',
        ),
        migrations.CreateModel(
            name='SellerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Wallet Label (e.g. Primary ETH Treasury, Solana Cold Storage, Business BTC)', max_length=100)),
                ('currency', models.CharField(choices=[('ETH', 'Ethereum (ETH)'), ('SOL', 'Solana (SOL)'), ('BTC', 'Bitcoin (BTC)'), ('USDT', 'Tether (USDT)'), ('BNB', 'BNB Smart Chain (BNB)'), ('MATIC', 'Polygon (MATIC)'), ('OTHER', 'Other Crypto')], default='ETH', max_length=20)),
                ('wallet_address', models.CharField(max_length=128)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default wallet for this currency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
